version: '3.8'

services:
  robot-monitoring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DEVICE=cuda
    restart: unless-stopped